version: '3.7'

services:
  # Connecting main app
  main:
    container_name: ndjs-diplom-app
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    restart: on-failure
    ports:
     - ${HTTP_PORT}:${HTTP_PORT}
    networks:
      - webnet
    depends_on:
      - mongo-storage
    command: npm run start:dev

  mongo-storage:
    container_name: mongo-storage
    image: mongo
    networks:
      - webnet
    restart: on-failure
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    ports:
    - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    volumes:
      - ./mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    networks:
      - webnet
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_SERVER: mongo-storage
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_HOST}:${MONGO_PORT}
    depends_on:
      mongo-storage:
        condition: service_healthy
    
networks:
  webnet:
volumes:
  mongo:
  